// <auto-generated />
using System;
using EnergyPC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnergyPC.Data.Migrations
{
    [DbContext(typeof(EnergyDbContext))]
    [Migration("20260603194759_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("EnergyPC.Data.Entities.Reading", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Horodatage")
                        .HasColumnType("TEXT");

                    b.Property<int>("SensorTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Valeur")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("SensorTypeId", "Horodatage");

                    b.ToTable("Readings");
                });

            modelBuilder.Entity("EnergyPC.Data.Entities.SensorType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Famille")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Unite")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("SensorTypes");
                });

            modelBuilder.Entity("EnergyPC.Data.Entities.Reading", b =>
                {
                    b.HasOne("EnergyPC.Data.Entities.SensorType", "SensorType")
                        .WithMany("Readings")
                        .HasForeignKey("SensorTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SensorType");
                });

            modelBuilder.Entity("EnergyPC.Data.Entities.SensorType", b =>
                {
                    b.Navigation("Readings");
                });
#pragma warning restore 612, 618
        }
    }
}
